# Generated by Django 5.0.6 on 2024-06-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Name',
            new_name='name',
        ),
    ]
