# Generated by Django 5.0.6 on 2024-06-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtionalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('display', models.CharField(max_length=200)),
                ('videoRecording', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
    ]
