# Generated by Django 5.0.6 on 2024-06-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_addtionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtionalinfo',
            name='capacity',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='addtionalinfo',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='addtionalinfo',
            name='display',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='addtionalinfo',
            name='videoRecording',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='addtionalinfo',
            name='weight',
            field=models.TextField(max_length=2000),
        ),
    ]
