# Generated by Django 5.0.6 on 2024-06-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='area_code',
            new_name='areacode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='primary_phone',
            new_name='primaryphone',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='street_address',
            new_name='streetaddress',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
