# Generated by Django 5.0.6 on 2024-06-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_orderplace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
